namespace: namespace
appName: service

image:
  repository: repository/service
  tag: <IMAGE_TAG>

deploy:
  enabled: true
  replicaCount: 1

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

probes:
  liveness:
    enabled: false
    path: /actuator/health/readiness
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readiness:
    enabled: false
    path: /actuator/health/readiness
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 8080

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  averageUtilization: 80

ingress:
  enabled: false

env: