{{- if .Values.deploy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy.appName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "deploy.selectorLabels" . | nindent 4 }}
{{- end }}